use anyhow::{Context, bail};
use base64::{Engine, engine::general_purpose::STANDARD as B64};
use serde::{Deserialize, Serialize};
use std::{collections::HashMap, fs, path::Path};

#[derive(Debug, Serialize, Deserialize)]
pub struct Config {
    pub port: u16,
    pub store_path: String,
    pub admin_key: String, // base64 Ed25519 pubkey (32 bytes) — BASE: только reg/dereg
    /// EXTENDED admin-ключ (base64 Ed25519 pubkey): полное управление сервером
    /// (config, dialogues/prune). Хранится офлайн в панели, в онлайн-сервисы не
    /// передаётся. Если пусто — extended-операции отключены. Подписывает также
    /// masking-профили (на стороне панели). Заложено с запасом под ротацию.
    #[serde(default)]
    pub extended_admin_key: String,
    #[serde(default)]
    pub users: HashMap<String, String>, // username -> base64 pubkey
    /// UDP-адрес для встроенного STUN-сервера (формат `ip:port`). Если
    /// `null`/отсутствует — STUN-листенер не запускается. По умолчанию
    /// `0.0.0.0:3478` (стандартный STUN-порт).
    #[serde(default = "default_stun_bind")]
    pub stun_bind: Option<String>,
    /// Публичный IP, который TURN отдаёт в XOR-RELAYED-ADDRESS. Нужен, если
    /// `stun_bind` слушает `0.0.0.0`; если не задан, сервер отдаёт локальный
    /// адрес relay-сокета, а клиент попробует заменить unspecified IP хостом
    /// TURN-сервера.
    #[serde(default)]
    pub turn_public_ip: Option<String>,
    /// Диапазон UDP-портов для TURN relay-аллокаций, формат `"start-end"`
    /// (включительно). По умолчанию `null` — сервер берёт случайный
    /// эфемерный порт ОС. Нужно задать узкий диапазон, если сервер за NAT и
    /// надо вручную пробросить эти порты (DMZ/range port forwarding).
    /// Пример: `"41000-41099"`.
    #[serde(default)]
    pub turn_relay_port_range: Option<String>,
    /// Путь к JSON-файлу masking-профиля (schema-cover). Если задан — сервер
    /// разворачивает/запечатывает трафик по этому профилю; если `null` —
    /// используется встроенная food-маска (`FoodDeliveryCover`).
    #[serde(default)]
    pub masking_profile_path: Option<String>,
    /// Путь к nginx-конфигу, в котором сервер автогенерирует блок маршрутизации
    /// своих эндпоинтов (между маркерами `## >>> PARANOIA AUTOGENERATED …`).
    /// Позволяет бесшовно менять маскировку таргетов, не ломая раздельную
    /// маршрутизацию/декой-страницу. `null`/пусто → фича выключена.
    #[serde(default)]
    pub nginx_config_path: Option<String>,
    /// Команда перезагрузки nginx после обновления конфига (например
    /// `"nginx -s reload"` или `"systemctl reload nginx"`). Берётся ТОЛЬКО из
    /// этого конфига (доверенный источник), не из профиля. `null` → сервер
    /// только пишет файл и логирует «перезагрузите вручную».
    #[serde(default)]
    pub nginx_reload_command: Option<String>,
    /// Верхняя граница файла, который кладётся В ИСТОРИЮ диалога (байты). Файлы
    /// `<= max_history_file_size` шлются обычным чанкингом и хранятся постоянно.
    /// По умолчанию 20 МиБ.
    #[serde(default = "default_max_history_file_size")]
    pub max_history_file_size: u64,
    /// Жёсткая верхняя граница размера файла вообще (байты). Файлы в диапазоне
    /// `(max_history_file_size .. large_file_max]` передаются ЭФЕМЕРНО (вне
    /// истории, с TTL); файлы больше `large_file_max` отклоняются на клиенте.
    /// По умолчанию 2 ГиБ.
    #[serde(default = "default_large_file_max")]
    pub large_file_max: u64,
    /// Срок временного хранения эфемерных больших файлов «в ожидании скачивания»
    /// (секунды). По истечении reaper физически удаляет блобы. По умолчанию 24 ч.
    #[serde(default = "default_ephemeral_retention_secs")]
    pub ephemeral_retention_secs: u64,
}

fn default_stun_bind() -> Option<String> {
    Some("0.0.0.0:3478".to_string())
}

fn default_max_history_file_size() -> u64 {
    20 * 1024 * 1024
}

fn default_large_file_max() -> u64 {
    2 * 1024 * 1024 * 1024
}

fn default_ephemeral_retention_secs() -> u64 {
    24 * 60 * 60
}

impl Config {
    pub fn load(path: &str) -> anyhow::Result<Self> {
        if !Path::new(path).exists() {
            let default = Self::default();
            default.save(path)?;
            return Ok(default);
        }
        let data =
            fs::read_to_string(path).with_context(|| format!("Cannot read config: {path}"))?;
        let cfg: Self = serde_json::from_str(&data).with_context(|| "Config JSON parse error")?;
        // Validate admin key
        let admin_bytes = B64
            .decode(&cfg.admin_key)
            .context("admin_key is not valid base64")?;
        if admin_bytes.len() != 32 {
            bail!("admin_key must be 32 bytes, got {}", admin_bytes.len());
        }
        Ok(cfg)
    }

    pub fn save(&self, path: &str) -> anyhow::Result<()> {
        if let Some(parent) = Path::new(path).parent() {
            fs::create_dir_all(parent)?;
        }
        let data = serde_json::to_string_pretty(self)?;
        fs::write(path, data)?;
        Ok(())
    }

    /// Decoded admin pubkey bytes (32 bytes).
    pub fn admin_pubkey_bytes(&self) -> anyhow::Result<[u8; 32]> {
        let v = B64.decode(&self.admin_key)?;
        Ok(v.try_into()
            .map_err(|_| anyhow::anyhow!("Bad admin key len"))?)
    }

    /// Decoded EXTENDED admin pubkey bytes (32 bytes). `None`, если не задан или
    /// некорректен — тогда extended-операции отключены.
    pub fn extended_admin_pubkey_bytes(&self) -> Option<[u8; 32]> {
        let key = self.extended_admin_key.trim();
        if key.is_empty() {
            return None;
        }
        B64.decode(key).ok()?.try_into().ok()
    }

    /// Decoded user pubkey bytes (32 bytes), None if not registered.
    pub fn user_pubkey_bytes(&self, username: &str) -> Option<[u8; 32]> {
        let b64 = self.users.get(username)?;
        let v = B64.decode(b64).ok()?;
        v.try_into().ok()
    }
}

impl Default for Config {
    fn default() -> Self {
        Self {
            port: 1455,
            store_path: "store".into(),
            admin_key: String::new(),
            extended_admin_key: String::new(),
            users: HashMap::new(),
            stun_bind: default_stun_bind(),
            turn_public_ip: None,
            turn_relay_port_range: None,
            masking_profile_path: None,
            nginx_config_path: None,
            nginx_reload_command: None,
            max_history_file_size: default_max_history_file_size(),
            large_file_max: default_large_file_max(),
            ephemeral_retention_secs: default_ephemeral_retention_secs(),
        }
    }
}
