//! Автогенерация nginx-маршрутизации эндпоинтов сервера.
//!
//! Сервер ведёт В ЧУЖОМ nginx-конфиге только свой блок `location`-ов,
//! ограждённый маркерами. Это позволяет бесшовно менять маскировку таргетов
//! (пути из masking-профиля), не трогая декой-страницу и остальную раздельную
//! маршрутизацию. Всё за пределами маркеров не редактируется; если маркеров в
//! файле нет — сервер НЕ трогает файл (чтобы не покалечить конфиг).
//!
//! Безопасность: пути из профиля санитизируются строгим allowlist'ом перед
//! записью в nginx-директивы (защита от инъекции директив). Команда reload
//! берётся только из конфига сервера (доверенный источник), не из профиля.

use anyhow::{Result, bail};
use std::fs;
use tracing::{info, warn};

pub const BEGIN_MARKER: &str = "## >>> PARANOIA AUTOGENERATED ROUTES (managed by paranoia server; do not edit) >>>";
pub const END_MARKER: &str = "## <<< PARANOIA AUTOGENERATED ROUTES <<<";

/// Одна управляемая маршрутизация: точное совпадение (`location = /path`) или
/// префикс (`location /path/`).
pub struct Route {
    pub path: String,
    pub exact: bool,
}

/// Допустим ли путь для записи в nginx-конфиг. Только то, что естественно для
/// URL-пути и не может вырваться из директивы `location`.
pub fn is_safe_path(path: &str) -> bool {
    path.starts_with('/')
        && path.len() <= 256
        && path
            .bytes()
            .all(|b| b.is_ascii_alphanumeric() || matches!(b, b'/' | b'_' | b'.' | b'-'))
}

/// Сгенерировать блок маршрутов (вместе с маркерами) для backend на `port`.
/// Небезопасные пути пропускаются с предупреждением.
pub fn render_block(routes: &[Route], port: u16) -> String {
    let mut out = String::new();
    out.push_str(BEGIN_MARKER);
    out.push('\n');
    for r in routes {
        if !is_safe_path(&r.path) {
            warn!("nginx: skipping unsafe path {:?}", r.path);
            continue;
        }
        let matcher = if r.exact {
            format!("location = {}", r.path)
        } else {
            format!("location {}", r.path)
        };
        out.push_str(&format!(
            "{matcher} {{\n    \
             proxy_pass http://127.0.0.1:{port};\n    \
             proxy_set_header Host $host;\n    \
             proxy_set_header X-Real-IP $remote_addr;\n    \
             proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\n    \
             proxy_set_header X-Forwarded-Proto https;\n    \
             proxy_http_version 1.1;\n    \
             proxy_buffering off;\n    \
             proxy_ssl_verify off;\n}}\n"
        ));
    }
    out.push_str(END_MARKER);
    out.push('\n');
    out
}

/// Заменить содержимое между маркерами (включая сами маркеры) на `block`.
/// Возвращает обновлённый текст. Ошибка, если маркеры отсутствуют или порядок
/// нарушен — вызывающий тогда НЕ перезаписывает файл.
pub fn replace_managed_region(existing: &str, block: &str) -> Result<String> {
    let begin = existing
        .find(BEGIN_MARKER)
        .ok_or_else(|| anyhow::anyhow!("begin marker not found"))?;
    let end_marker_pos = existing
        .find(END_MARKER)
        .ok_or_else(|| anyhow::anyhow!("end marker not found"))?;
    if end_marker_pos < begin {
        bail!("end marker precedes begin marker");
    }
    let end = end_marker_pos + END_MARKER.len();
    // Поглощаем завершающий перевод строки после END-маркера, если есть, —
    // render_block добавляет свой.
    let after = existing[end..].strip_prefix('\n').unwrap_or(&existing[end..]);
    let mut result = String::with_capacity(begin + block.len() + after.len());
    result.push_str(&existing[..begin]);
    result.push_str(block);
    result.push_str(after);
    Ok(result)
}

/// Обновить управляемый блок в nginx-конфиге и (опционально) перезагрузить
/// nginx. Без паники: любые ошибки логируются, сервер продолжает работу.
pub fn update(config_path: &str, routes: &[Route], port: u16, reload_command: Option<&str>) {
    let existing = match fs::read_to_string(config_path) {
        Ok(s) => s,
        Err(e) => {
            warn!("nginx: cannot read {config_path}: {e} — skipping route sync");
            return;
        }
    };
    let block = render_block(routes, port);
    let updated = match replace_managed_region(&existing, &block) {
        Ok(s) => s,
        Err(e) => {
            warn!(
                "nginx: markers not found/invalid in {config_path}: {e} — \
                 add the PARANOIA AUTOGENERATED markers to enable route sync"
            );
            return;
        }
    };
    if updated == existing {
        return; // нечего менять
    }
    if let Err(e) = fs::write(config_path, &updated) {
        warn!("nginx: cannot write {config_path}: {e}");
        return;
    }
    info!("nginx: synced {} managed routes in {config_path}", routes.len());
    reload(reload_command);
}

fn reload(reload_command: Option<&str>) {
    let Some(cmd) = reload_command.filter(|c| !c.trim().is_empty()) else {
        info!("nginx: no reload command configured — reload manually to apply");
        return;
    };
    // Команда из доверенного конфига сервера. Запускаем через sh -c.
    match std::process::Command::new("sh").arg("-c").arg(cmd).status() {
        Ok(st) if st.success() => info!("nginx: reloaded via `{cmd}`"),
        Ok(st) => warn!("nginx: reload command `{cmd}` exited with {st}"),
        Err(e) => warn!("nginx: failed to run reload command `{cmd}`: {e}"),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn routes() -> Vec<Route> {
        vec![
            Route { path: "/v2/orders".into(), exact: true },
            Route { path: "/admin/".into(), exact: false },
        ]
    }

    #[test]
    fn rejects_unsafe_paths() {
        assert!(is_safe_path("/v2/orders"));
        assert!(is_safe_path("/admin/"));
        assert!(!is_safe_path("/x; }\nevil"));
        assert!(!is_safe_path("/a b"));
        assert!(!is_safe_path("relative"));
    }

    #[test]
    fn block_contains_markers_and_routes() {
        let b = render_block(&routes(), 1455);
        assert!(b.starts_with(BEGIN_MARKER));
        assert!(b.trim_end().ends_with(END_MARKER));
        assert!(b.contains("location = /v2/orders"));
        assert!(b.contains("location /admin/"));
        assert!(b.contains("proxy_pass http://127.0.0.1:1455;"));
    }

    #[test]
    fn unsafe_path_is_skipped_in_block() {
        let bad = vec![Route { path: "/ok".into(), exact: true }, Route { path: "/bad;}".into(), exact: true }];
        let b = render_block(&bad, 80);
        assert!(b.contains("location = /ok"));
        assert!(!b.contains("/bad"));
    }

    #[test]
    fn replace_preserves_surrounding_config() {
        let existing = format!(
            "server {{\n  location / {{ root /var/www/decoy; }}\n  {BEGIN_MARKER}\n  location = /old {{ proxy_pass http://x; }}\n  {END_MARKER}\n  ssl_certificate /c;\n}}\n"
        );
        let block = render_block(&[Route { path: "/new".into(), exact: true }], 1455);
        let updated = replace_managed_region(&existing, &block).unwrap();
        assert!(updated.contains("location / { root /var/www/decoy; }"));
        assert!(updated.contains("ssl_certificate /c;"));
        assert!(updated.contains("location = /new"));
        assert!(!updated.contains("/old"));
    }

    #[test]
    fn missing_markers_is_error() {
        assert!(replace_managed_region("server { }", "block").is_err());
    }

    #[test]
    fn replace_is_idempotent() {
        let existing = format!("a\n{BEGIN_MARKER}\nstale\n{END_MARKER}\nb\n");
        let block = render_block(&[Route { path: "/p".into(), exact: true }], 80);
        let once = replace_managed_region(&existing, &block).unwrap();
        let twice = replace_managed_region(&once, &block).unwrap();
        assert_eq!(once, twice);
    }
}
