import { VerticalBox, Button } from "std-widgets.slint";

export component ConnectScreen inherits VerticalBox {

    callback admin();
    callback client();
    min-width: 640px;
    min-height: 960px;
    
    spacing: 12px;

    Text {
        text: "Подключиться";
        font-size: 20px;
    }

    Button {
        text: "Админ";
        clicked => admin();
    }

    Button {
        text: "Клиент";
        clicked => client();
    }
}
