import {
    VerticalBox,
    HorizontalBox,
    Button,
    LineEdit,
} from "std-widgets.slint";

export component DialogueView inherits VerticalBox {
    callback send(string);

    spacing: 5px;  
    padding: 0;

    VerticalBox {
        min-width: 640px;
        min-height: 800px;

        Text {
            text: "Messages area";
        }
    }

    Rectangle {
        border-color: #ffffff;
        HorizontalBox {
            padding: 0;
            spacing: 0px;

            input_text_edit := LineEdit {
                opacity: 100;
                placeholder-text: "Введите сообщение";
            }

            Button {
                icon: @image-url("../icons/send.svg");
                icon-size: 24px;
                clicked => {
                    debug("Text edited: ", input_text_edit.text);
                    root.send(input_text_edit.text);
                }
            }
        }
    }
}
