import { VerticalBox, HorizontalBox, Button, LineEdit, Text } from "std-widgets.slint";

export component DialogueView inherits VerticalBox {

    in property <string> input-text;
    callback send(string text);

    spacing: 8px;

    VerticalBox {
        height: 550px;
        Text { text: "Messages area"; }
    }

    HorizontalBox {
        spacing: 4px;

        LineEdit {
            placeholder-text: "Введите сообщение";
            text <=> root.input-text;
        }

        Button {
            text: "Send";
            clicked => root.send(root.input-text);
        }
    }
}