import {
    VerticalBox,
    LineEdit,
    Button,
    ProgressIndicator,
} from "std-widgets.slint";

export component InstallServerScreen inherits VerticalBox {
    in property <float> progress: 0.0;

    callback start-install(string, string, string, string, string);
    min-width: 640px;
    min-height: 960px;
    spacing: 8px;

    Text {
        text: "Установка сервера";
        font-size: 20px;
    }

    inputBox := VerticalBox {
        property <bool> input-enabled: true;

        domain := LineEdit {
            enabled: input-enabled;
            placeholder-text: "Домен";
        }

        ip := LineEdit {
            enabled: input-enabled;
            placeholder-text: "IP";
        }

        user := LineEdit {
            enabled: input-enabled;
            placeholder-text: "Username";
        }

        pass := LineEdit {
            enabled: input-enabled;
            placeholder-text: "Password";
            input-type: password;
        }

        port := LineEdit {
            enabled: input-enabled;
            placeholder-text: "Port";
            input-type: decimal;
            text: "1455";
        }

        install := Button {
            text: "Установить";
            clicked => {
                root.start-install(domain.text, ip.text, user.text, pass.text, port.text);
                inputBox.input-enabled = false;
            }
        }
    }

    ProgressIndicator {
        progress: root.progress;
    }
}
