import { VerticalBox, LineEdit, Button } from "std-widgets.slint";

export component LoginScreen inherits VerticalBox {

    in property <string> server;
    in property <string> key;

    callback login(string, string);
    
    min-width: 640px;
    min-height: 960px;
    spacing: 8px;

    Text {
        text: "Вход";
        font-size: 20px;
    }

    server := LineEdit {
        placeholder-text: "Server (domain:port)";
    }

    key := LineEdit {
        placeholder-text: "Private key";
    }

    Button {
        text: "Войти";
        clicked => root.login(server.text, key.text);
    }
}
