import { VerticalBox, LineEdit, Button, Text } from "std-widgets.slint";

export component LoginScreen inherits VerticalBox {

    in property <string> server;
    in property <string> key;

    callback login(string server, string key);

    spacing: 8px;

    Text { text: "Вход"; font-size: 20px; }

    LineEdit { placeholder-text: "Server (domain:port)"; text <=> root.server; }
    LineEdit { placeholder-text: "Private key"; text <=> root.key; }

    Button {
        text: "Войти";
        clicked => root.login(root.server, root.key);
    }
}