import { VerticalBox } from "std-widgets.slint";
import { HelloScreen } from "hello.slint";
import { InstallServerScreen } from "install_server.slint";
import { ConnectScreen } from "connect.slint";
import { RegisterScreen } from "register.slint";
import { LoginScreen } from "login.slint";
import { MainTabs } from "main_tabs.slint";

export enum Screen {
    Hello,
    Install,
    Connect,
    Register,
    Login,
    Main
}

export component MainWindow inherits Window {
    min-width: 640px;
    min-height: 960px;
    title: "Paranoia";

    in-out property <Screen> current-screen: Screen.Hello;

    callback start-install(string, string, string, string, string);
    callback client_login(string, string);

    VerticalBox {
        padding: 16px;
        spacing: 8px;

        if root.current-screen == Screen.Hello:
            HelloScreen {
            connect => {
                root.current-screen = Screen.Connect;
            }
            install => {
                root.current-screen = Screen.Install;
            }
        }

        if root.current-screen == Screen.Install:
            InstallServerScreen {
            start-install(domain, ip, user, pass, port) => {
                root.start-install(domain, ip, user, pass, port);
            }
        }

        if root.current-screen == Screen.Connect:
            ConnectScreen {
            admin => {
                root.current-screen = Screen.Login;
            }
            client => {
                root.current-screen = Screen.Register;
            }
        }

        if root.current-screen == Screen.Register:
            RegisterScreen {
            done => {
                root.current-screen = Screen.Login;
            }
        }

        if root.current-screen == Screen.Login:
            LoginScreen {
            login(server, key) => root.client_login(server, key);
        }

        if (root.current-screen == Screen.Main): MainTabs { }
    }
}
