import {
    VerticalBox,
    HorizontalBox,
    Button,
    TabWidget,
} from "std-widgets.slint";
import { DialogueView } from "dialogue.slint";

export component MainTabs inherits VerticalBox {

    spacing: 4px;
    min-width: 640px;
    min-height: 960px;

    TabWidget {
        min-width: 640px;
        min-height: 960px;
        Tab {
            title: "User";
            DialogueView { }
        }

        Tab {
            title: "Admin";
            VerticalBox {
                Text {
                    text: "Admin Panel";
                }

                Button {
                    text: "Register user";
                }
            }
        }

        Tab {
            title: "+";
            VerticalBox {
                Text {
                    text: "Add Dialogue";
                }

                Button {
                    text: "Scan QR";
                }

                Button {
                    text: "Show my QR";
                }
            }
        }
    }
}
