import { VerticalBox } from "std-widgets.slint";
import { HelloScreen } from "hello.slint";
import { InstallServerScreen } from "install_server.slint";
import { ConnectScreen } from "connect.slint";
import { RegisterScreen } from "register.slint";
import { LoginScreen } from "login.slint";
import { MainTabs } from "main_tabs.slint";
import { HeaderWithBack } from "header.slint";

export enum Screen {
    Hello,
    Install,
    Connect,
    Register,
    Login,
    Main
}

export component MainWindow inherits Window {
    min-width: 640px;
    min-height: 960px;
    title: "Paranoia";

    in-out property <Screen> current-screen: Screen.Hello;

    /// Навигация со стеком
    callback navigate_to(Screen);
    callback go_back(); 
    /// Навигация

    callback start-install(string, string, string, string, string);
    callback client_login(string, string);

    VerticalBox {
        padding: 16px;
        spacing: 8px;
        HeaderWithBack {
            back => go_back();
        }

        if root.current-screen == Screen.Hello:
            HelloScreen {
            connect => navigate_to(Screen.Connect);
            install => navigate_to(Screen.Install);
        }

        if root.current-screen == Screen.Install:
            InstallServerScreen {
            start-install(domain, ip, user, pass, port) => {
                root.start-install(domain, ip, user, pass, port);
            }
        }

        if root.current-screen == Screen.Connect:
            ConnectScreen {
            admin => navigate_to(Screen.Login);
            client => navigate_to(Screen.Register);
        }

        if root.current-screen == Screen.Register:
            RegisterScreen {
            done => navigate_to(Screen.Login);
        }

        if root.current-screen == Screen.Login:
            LoginScreen {
            login(server, key) => root.client_login(server, key);
        }

        if (root.current-screen == Screen.Main): MainTabs { }
    }
}
