import { VerticalBox } from "std-widgets.slint";
import "./hello.slint";
import "./install_server.slint";
import "./connect.slint";
import "./register.slint";
import "./login.slint";
import "./main_tabs.slint";

export enum Screen {
    Hello,
    Install,
    Connect,
    Register,
    Login,
    Main
}

export component MainWindow inherits Window {
    width: 420px;
    height: 720px;
    title: "Paranoia";

    in-out property <Screen> current-screen: Screen.Hello;

    callback start-install(string domain, string ip, string user, string pass, int port);
    callback client_login(string server, string key);

    VerticalBox {
        padding: 16px;
        spacing: 8px;

        if (root.current-screen == Screen.Hello) {
            HelloScreen {
                connect => root.current-screen = Screen.Connect;
                install => root.current-screen = Screen.Install;
            }
        }

        if (root.current-screen == Screen.Install) {
            InstallServerScreen {
                start-install => root.start-install(domain, ip, user, pass, port);
            }
        }

        if (root.current-screen == Screen.Connect) {
            ConnectScreen {
                admin => root.current-screen = Screen.Login;
                client => root.current-screen = Screen.Register;
            }
        }

        if (root.current-screen == Screen.Register) {
            RegisterScreen {
                done => root.current-screen = Screen.Login;
            }
        }

        if (root.current-screen == Screen.Login) {
            LoginScreen {
                login => root.client_login(server, key);
            }
        }

        if (root.current-screen == Screen.Main) {
            MainTabs { }
        }
    }
}