import { VerticalBox, Button } from "std-widgets.slint";

export component RegisterScreen inherits VerticalBox {

    in property <string> pubkey;
    callback done();

    min-width: 640px;
    min-height: 960px;
    spacing: 12px;

    Text { text: "Регистрация"; font-size: 20px; }

    Text {
        text: "Передайте администратору этот ключ:";
        wrap: word-wrap;
    }

    Text {
        text: root.pubkey;
        wrap: word-wrap;
        font-size: 12px;
    }

    Button {
        text: "Продолжить";
        clicked => done();
    }
}