echo "Настройка nginx → Paranoia"
sudo -n true
sudo cat > /etc/nginx/conf.d/paranoia.conf << 'EOF'
map $http_upgrade $connection_upgrade {
    default upgrade;
    ''      close;
}

server {
    listen 80;
    server_name {DOMAIN};

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 444;
    }
}

server {
    listen 443 ssl http2;
    server_name {DOMAIN};

    ssl_certificate     /etc/letsencrypt/live/{DOMAIN}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/{DOMAIN}/privkey.pem;

    client_max_body_size 1024M;

    # Раздельная маршрутизация таржетов: ниже — управляемый сервером блок с
    # эндпоинтами Paranoia. Сервер может перегенерировать ТОЛЬКО область между
    # маркерами при смене маскировки (если в Paranoia.json задан
    # nginx_config_path). Ничего вне маркеров он не трогает. Маркеры менять/
    # удалять нельзя — иначе авто-синхронизация отключится.
    ## >>> PARANOIA AUTOGENERATED ROUTES (managed by paranoia server; do not edit) >>>
    location = /reg            { proxy_pass http://127.0.0.1:{PARANOIA_PORT}; proxy_set_header Host $host; proxy_set_header X-Real-IP $remote_addr; proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; proxy_set_header X-Forwarded-Proto https; proxy_http_version 1.1; proxy_buffering off; proxy_ssl_verify off; }
    location = /push           { proxy_pass http://127.0.0.1:{PARANOIA_PORT}; proxy_set_header Host $host; proxy_set_header X-Real-IP $remote_addr; proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; proxy_set_header X-Forwarded-Proto https; proxy_http_version 1.1; proxy_buffering off; proxy_ssl_verify off; }
    location = /pull           { proxy_pass http://127.0.0.1:{PARANOIA_PORT}; proxy_set_header Host $host; proxy_set_header X-Real-IP $remote_addr; proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; proxy_set_header X-Forwarded-Proto https; proxy_http_version 1.1; proxy_buffering off; proxy_ssl_verify off; }
    location = /map            { proxy_pass http://127.0.0.1:{PARANOIA_PORT}; proxy_set_header Host $host; proxy_set_header X-Real-IP $remote_addr; proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; proxy_set_header X-Forwarded-Proto https; proxy_http_version 1.1; proxy_buffering off; proxy_ssl_verify off; }
    location = /notify         { proxy_pass http://127.0.0.1:{PARANOIA_PORT}; proxy_set_header Host $host; proxy_set_header X-Real-IP $remote_addr; proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; proxy_set_header X-Forwarded-Proto https; proxy_http_version 1.1; proxy_buffering off; proxy_ssl_verify off; }
    location = /determinate    { proxy_pass http://127.0.0.1:{PARANOIA_PORT}; proxy_set_header Host $host; proxy_set_header X-Real-IP $remote_addr; proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; proxy_set_header X-Forwarded-Proto https; proxy_http_version 1.1; proxy_buffering off; proxy_ssl_verify off; }
    location = /arrived        { proxy_pass http://127.0.0.1:{PARANOIA_PORT}; proxy_set_header Host $host; proxy_set_header X-Real-IP $remote_addr; proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; proxy_set_header X-Forwarded-Proto https; proxy_http_version 1.1; proxy_buffering off; proxy_ssl_verify off; }
    location = /call/signal    { proxy_pass http://127.0.0.1:{PARANOIA_PORT}; proxy_set_header Host $host; proxy_set_header X-Real-IP $remote_addr; proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; proxy_set_header X-Forwarded-Proto https; proxy_http_version 1.1; proxy_buffering off; proxy_ssl_verify off; }
    location = /call/poll      { proxy_pass http://127.0.0.1:{PARANOIA_PORT}; proxy_set_header Host $host; proxy_set_header X-Real-IP $remote_addr; proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; proxy_set_header X-Forwarded-Proto https; proxy_http_version 1.1; proxy_buffering off; proxy_ssl_verify off; }
    location /admin/           { proxy_pass http://127.0.0.1:{PARANOIA_PORT}; proxy_set_header Host $host; proxy_set_header X-Real-IP $remote_addr; proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; proxy_set_header X-Forwarded-Proto https; proxy_http_version 1.1; proxy_buffering off; proxy_ssl_verify off; }
    ## <<< PARANOIA AUTOGENERATED ROUTES <<<

    # Слот под маскировку (декой). По умолчанию проксирует на backend — сервер
    # отдаёт 404 на неизвестные пути. Для маскировочной страницы замените тело
    # этого блока на отдачу статического сайта, напр.:
    #   root /var/www/decoy; index index.html; try_files $uri $uri/ =404;
    location / {
        proxy_pass http://127.0.0.1:{PARANOIA_PORT};
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_http_version 1.1;
        proxy_buffering off;
        proxy_ssl_verify off;
    }

}
EOF
sudo service nginx restart
